# Build and Run tests
build:
    mvn clean verify

# Build without test
quick:
    mvn clean package -DskipTests

# Launch dev mode
dev:
    mvn quarkus:dev

run: quick
    docker compose up -d
    java -Djdk.tracePinnedThreads=full -Dpulsar.url=pulsar://localhost:6650  -Dquarkus.redis.hosts=redis://localhost:6379 -jar target/quarkus-app/quarkus-run.jar

stop:
  docker compose down
